defmodule Omedis.Repo.Migrations.AddReferencesToGroupUserTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:group_users, "group_users_user_id_fkey")

    drop constraint(:group_users, "group_users_group_id_fkey")

    alter table(:group_users) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_users_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "group_users_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:access_rights, "access_rights_group_id_fkey")

    drop constraint(:access_rights, "access_rights_tenant_id_fkey")

    alter table(:access_rights) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "access_rights_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "access_rights_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:access_rights, "access_rights_tenant_id_fkey")

    drop constraint(:access_rights, "access_rights_group_id_fkey")

    alter table(:access_rights) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "access_rights_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "access_rights_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:group_users, "group_users_group_id_fkey")

    drop constraint(:group_users, "group_users_user_id_fkey")

    alter table(:group_users) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "group_users_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_users_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
