defmodule Omedis.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :lang, :text, null: false, default: "en"
    end
  end

  def down do
    alter table(:users) do
      remove :lang
    end
  end
end
