defmodule Omedis.Repo.Migrations.DropActivities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """
  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:activities, [:color_code, :group_id],
                     name: "activities_unique_color_code_position_index"
                   )

    drop_if_exists unique_index(:activities, [:position, :group_id],
                     name: "activities_unique_position_index"
                   )

    drop_if_exists unique_index(:activities, [:slug, :group_id],
                     name: "activities_unique_slug_index"
                   )

    alter table(:log_entries) do
      remove :activity_id
    end

    drop table(:activities)
  end

  def down do
    create table(:activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :group_id, references(:groups, type: :uuid, on_delete: :delete_all), null: false
      add :project_id, references(:projects, type: :uuid, on_delete: :delete_all), null: false
      add :color_code, :text
      add :is_default, :boolean, default: false
      add :position, :text
      add :slug, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:activities, [:color_code, :group_id],
             name: "activities_unique_color_code_position_index"
           )

    create unique_index(:activities, [:position, :group_id],
             name: "activities_unique_position_index"
           )

    create unique_index(:activities, [:slug, :group_id], name: "activities_unique_slug_index")

    alter table(:log_entries) do
      add :activity_id,
          references(:activities,
            column: :id,
            name: "log_entries_activity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
