defmodule Omedis.Repo.Migrations.MigrateResources18 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:log_entries) do
      add :is_default, :boolean
    end
  end

  def down do
    alter table(:log_entries) do
      remove :is_default
    end
  end
end
