defmodule Omedis.Repo.Migrations.AddStatusToInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:invitations) do
      add :status, :text, null: false, default: "pending"
    end
  end

  def down do
    alter table(:invitations) do
      remove :status
    end
  end
end
