defmodule Omedis.Repo.Migrations.AddUniqueIndexToGroupUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:group_users, [:group_id, :user_id],
             name: "group_users_unique_group_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_users, [:group_id, :user_id],
                     name: "group_users_unique_group_user_index"
                   )
  end
end
