defmodule Omedis.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :slug, :text
    end
  end

  def down do
    alter table(:tenants) do
      remove :slug
    end
  end
end
