defmodule Omedis.Repo.Migrations.RelateLogEntriesToActivities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:log_entries, "log_entries_activity_id_fkey")

    alter table(:log_entries) do
      modify :activity_id, :uuid
    end

    alter table(:log_entries) do
      remove :activity_id
    end

    rename table(:log_entries), :log_category_id, to: :activity_id
  end

  def down do
    rename table(:log_entries), :activity_id, to: :log_category_id

    alter table(:log_entries) do
      add :activity_id, :uuid
    end

    alter table(:log_entries) do
      modify :activity_id,
             references(:activities,
               column: :id,
               name: "log_entries_activity_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             ),
             null: true
    end
  end
end
