defmodule Omedis.Repo.Migrations.UpdatePositionType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop the existing index first
    drop_if_exists index(:log_categories, [:position, :group_id],
                     name: :log_categories_unique_position_index
                   )

    # Modify column with explicit USING clause
    execute "ALTER TABLE log_categories ALTER COLUMN position TYPE bigint USING position::bigint"

    # Recreate the index
    create unique_index(:log_categories, [:position, :group_id],
             name: :log_categories_unique_position_index
           )
  end

  def down do
    drop_if_exists index(:log_categories, [:position, :group_id],
                     name: :log_categories_unique_position_index
                   )

    execute "ALTER TABLE log_categories ALTER COLUMN position TYPE varchar USING position::varchar"

    create unique_index(:log_categories, [:position, :group_id],
             name: :log_categories_unique_position_index
           )
  end
end
