defmodule Omedis.Repo.Migrations.RegenerateMissingSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    :ok
  end
end
