defmodule Omedis.Repo.Migrations.MigrateResources18 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "groups_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "groups_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:groups, "groups_tenant_id_fkey")

    drop constraint(:groups, "groups_user_id_fkey")

    drop table(:groups)
  end
end
