defmodule Omedis.Repo.Migrations.AddDailyStartAndEndTimesToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :daily_start_at, :time
      add :daily_end_at, :time
    end

    rename table(:tenants), :daily_start_at, to: :default_daily_start_at
    rename table(:tenants), :daily_end_at, to: :default_daily_end_at
  end

  def down do
    rename table(:tenants), :default_daily_end_at, to: :daily_end_at
    rename table(:tenants), :default_daily_start_at, to: :daily_start_at

    alter table(:users) do
      remove :daily_end_at
      remove :daily_start_at
    end
  end
end
