defmodule Omedis.Repo.Migrations.CreateGroupUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_users, primary_key: false) do
      add :group_id,
          references(:groups,
            column: :id,
            name: "group_users_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "group_users_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:group_users, "group_users_group_id_fkey")

    drop constraint(:group_users, "group_users_user_id_fkey")

    drop table(:group_users)
  end
end
