defmodule Omedis.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :daily_start_at, :time, default: fragment("'08:00:00'")
      add :daily_end_at, :time, default: fragment("'17:00:00'")
    end
  end

  def down do
    alter table(:tenants) do
      remove :daily_end_at
      remove :daily_start_at
    end
  end
end
