defmodule Omedis.Repo.Migrations.LogCategorySlugsAreNotUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:log_categories, [:slug, :group_id],
             name: "log_categories_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:log_categories, [:slug, :group_id],
                     name: "log_categories_unique_slug_index"
                   )
  end
end
