defmodule Omedis.Repo.Migrations.ChangeSlugDatatypeToCitext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      modify :slug, :citext
    end

    alter table(:tenants) do
      modify :slug, :citext
    end
  end

  def down do
    alter table(:groups) do
      modify :slug, :text
    end

    alter table(:tenants) do
      modify :slug, :text
    end
  end
end
