defmodule Omedis.Repo.Migrations.NullableOrganisationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organisations) do
      modify :country, :text, null: true
      modify :city, :text, null: true
      modify :zip_code, :text, null: true
      modify :street, :text, null: true
    end
  end

  def down do
    alter table(:organisations) do
      modify :street, :text, null: false
      modify :zip_code, :text, null: false
      modify :city, :text, null: false
      modify :country, :text, null: false
    end
  end
end
