defmodule Omedis.Repo.Migrations.UpdateAccessRightsTenantIdConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:access_rights, "access_rights_tenant_id_fkey")

    alter table(:access_rights) do
      modify :tenant_id, references(:tenants, type: :uuid, on_delete: :delete_all)
    end
  end

  def down do
    drop constraint(:access_rights, "access_rights_tenant_id_fkey")

    alter table(:access_rights) do
      modify :tenant_id, references(:tenants, type: :uuid)
    end
  end
end
