defmodule Omedis.Repo.Migrations.UniqueInvitationEmailIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:invitations) do
      modify :email, :citext
    end

    create unique_index(:invitations, [:organisation_id, :email],
             name: "invitations_unique_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:invitations, [:organisation_id, :email],
                     name: "invitations_unique_email_index"
                   )

    alter table(:invitations) do
      modify :email, :text
    end
  end
end
