defmodule Omedis.Repo.Migrations.AddReferencesToInvitationGroupTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:invitation_groups, "invitation_groups_group_id_fkey")

    drop constraint(:invitation_groups, "invitation_groups_invitation_id_fkey")

    alter table(:invitation_groups) do
      modify :invitation_id,
             references(:invitations,
               column: :id,
               name: "invitation_groups_invitation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "invitation_groups_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:invitation_groups, "invitation_groups_invitation_id_fkey")

    drop constraint(:invitation_groups, "invitation_groups_group_id_fkey")

    alter table(:invitation_groups) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "invitation_groups_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invitation_id,
             references(:invitations,
               column: :id,
               name: "invitation_groups_invitation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
