defmodule Omedis.Repo.Migrations.UpdatePositionType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:log_categories) do
      remove :position
      add :position, :bigint
    end
  end

  def down do
    alter table(:log_categories) do
      add :position, :string
    end
  end
end
