defmodule Omedis.Repo.Migrations.AddReferencesToGroupUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:group_users, "group_users_user_id_fkey")

    drop constraint(:group_users, "group_users_group_id_fkey")

    drop constraint("group_users", "group_users_pkey")

    alter table(:log_categories) do
      modify :position, :bigint
    end

    alter table(:group_users) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_users_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "group_users_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint("group_users", "group_users_pkey")

    drop constraint(:group_users, "group_users_group_id_fkey")

    drop constraint(:group_users, "group_users_user_id_fkey")

    alter table(:group_users) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "group_users_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_users_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:log_categories) do
      modify :position, :text
    end
  end
end
