defmodule Omedis.Repo.Migrations.MigrateResources20 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:log_entries) do
      modify :is_default, :boolean, null: true
    end
  end

  def down do
    alter table(:log_entries) do
      modify :is_default, :boolean, null: false
    end
  end
end
