defmodule Omedis.Repo.Migrations.AddDailyStartAndEndTimesToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :daily_start_at, :time, default: fragment("'08:00:00'")
      add :daily_end_at, :time, default: fragment("'18:00:00'")
    end

    rename table(:tenants), :daily_start_at, to: :default_daily_start_at

    rename table(:tenants), :daily_end_at, to: :default_daily_end_at

    alter table(:tenants) do
      modify :default_daily_end_at, :time, default: nil
      modify :default_daily_start_at, :time, default: nil
    end
  end

  def down do
    alter table(:tenants) do
      modify :daily_start_at, :time, default: fragment("'08:00:00'")
      modify :daily_end_at, :time, default: fragment("'18:00:00'")
    end

    rename table(:tenants), :default_daily_end_at, to: :daily_end_at

    rename table(:tenants), :default_daily_start_at, to: :daily_start_at

    alter table(:users) do
      remove :daily_end_at
      remove :daily_start_at
    end
  end
end
