defmodule Omedis.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :comment, :text

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "log_entries_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :log_category_id,
          references(:log_categories,
            column: :id,
            name: "log_entries_log_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "log_entries_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :start_at, :time
      add :end_at, :time

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:log_entries, "log_entries_tenant_id_fkey")

    drop constraint(:log_entries, "log_entries_log_category_id_fkey")

    drop constraint(:log_entries, "log_entries_user_id_fkey")

    drop table(:log_entries)
  end
end
