defmodule Omedis.Repo.Migrations.CreateAccessRights do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_rights, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_name, :text, null: false
      add :read, :boolean, default: false
      add :write, :boolean, default: false
      add :update, :boolean, default: false
      add :create, :boolean, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "access_rights_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :group_id,
          references(:groups,
            column: :id,
            name: "access_rights_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:access_rights, "access_rights_tenant_id_fkey")

    drop constraint(:access_rights, "access_rights_group_id_fkey")

    drop table(:access_rights)
  end
end
