defmodule Omedis.Repo.Migrations.FixGroupsSlugUniquenessScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:groups, [:slug], name: "groups_unique_slug_index")

    create unique_index(:groups, [:slug, :tenant_id], name: "groups_unique_slug_per_tenant_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:slug, :tenant_id],
                     name: "groups_unique_slug_per_tenant_index"
                   )

    create unique_index(:groups, [:slug], name: "groups_unique_slug_index")
  end
end
