defmodule Omedis.Repo.Migrations.AddStatusToInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @status_types ~w(accepted expired pending)

  def up do
    execute(
      "CREATE TYPE invitation_status AS ENUM (#{Enum.map_join(@status_types, ", ", &"'#{&1}'")})"
    )

    alter table(:invitations) do
      add :status, :invitation_status, null: false, default: "pending"
    end
  end

  def down do
    alter table(:invitations) do
      remove :status
    end

    execute("DROP TYPE invitation_status")
  end
end
