defmodule Omedis.Repo.Migrations.RenameUniqueActivityColorIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:activities, [:organisation_id, :color_code, :group_id],
                     name: "activities_unique_color_code_position_index"
                   )
  end

  def down do
    create unique_index(:activities, [:organisation_id, :color_code, :group_id],
             name: "activities_unique_color_code_position_index"
           )
  end
end
