name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}

    env:
      MIX_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: omedis_test

    strategy:
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.17.2"]

    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: omedis_test
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check for changes in gettext files
        run: make check-gettext

      - name: Check migrations
        run: mix ash_postgres.generate_migrations --check

      - name: Check resource snapshots
        run: mix ash_postgres.squash_snapshots --check

      - name: Run tests
        env:
          CI: true
          DISABLE_ML_FEATURES: true
        run: mix test --cover --warnings-as-errors

      - name: Run Credo
        run: mix credo --strict
